/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyfigura;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Asullom
 */
public class NewJFrame extends javax.swing.JFrame {
Figura vector[];
   int N,h,w;
    /**
     * Creates new form MainFrame
     */
    public NewJFrame() {
        initComponents();
    llenar_vector();
        setTitle("FIGURAS UTILIZANDO POLIMORFISMO");
    }
 public void llenar_vector()
  {
    int i,x,y,r,alto,ancho;
    Color color;
    N=300;
    vector=new Figura[N];
    h= this.getHeight();
    w=this.getWidth();
  
    for(i=0;i<N;i++)
    {
       x=(int)(Math.random()*w);
       y=(int)(Math.random()*h);
       color=new Color((int)(Math.random()*250),(int)(Math.random()*250),(int)(Math.random()*250));
         if( (int)(Math.random()*2)==0)
         {
               r=(int)(Math.random()*30);
               vector[i]=new Circulo(x,y,r,color);
         }
         else
         {
               alto=(int)(Math.random()*30);
               ancho=(int)(Math.random()*30);
               vector[i]=new Rectangulo(x,y,alto,ancho,color);
         }
    }
   }
 public void paint(Graphics g)
{
      super.paint(g);
      g.setColor(Color.white);
      g.fillRect(0, 0, this.getWidth(), this.getHeight());
       for(int i=0;i<N;i++)
       {
          vector[i].pintar(g);
      }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
